[project]
name = "agent"
version = "0.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "additive-manufacturing",
]

[tool.uv.sources]
additive-manufacturing = { workspace = true }

