name: pytest

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Python using uv
      uses: astral-sh/uv-action@v1
      with:
        python-version: '3.10'

    - name: Install project dependencies
      run: |
        uv sync  # installs all packages added via `uv add`

    - name: Run tests
      run: |
        uv tool run pytest

